const resObj = [
    {
      id: 1,
      image: "https://www.thevellorekitchen.in/wp-content/uploads/2023/01/Hyderabadi-Chicken-Briyani.jpg",
      restaurantName: "Spicy Delights",
      cuisine: "Briyani,Indian",
      rating: 4.5,
      price: "$10 - $25",
      deliveryTime: "30-40 mins",
    },
    {
      id: 2,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0Lj3_8eh0xYQLDhyh1pYwOF6l00mL7hIfww&s",
      restaurantName: "Pizza Haven",
      cuisine: "Pizza,Italian",
      rating: 4.7,
      price: "$8 - $20",
      deliveryTime: "20-30 mins",
    },
    {
        id: 3,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfg9B6xzfanVTpi-C4uuDtjNfBxtZA9KA57w&s",
        restaurantName: "Burger King",
        cuisine: "Burger,Fast Food",
        rating: 4.2,
        price: "$5 - $15",
        deliveryTime: "15-25 mins",
    },
    {
        id: 4,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiCR8onF7CpL-elbCPQH-xbv6hDpj9Tx3E9g&s",
        restaurantName: "KFC",
        cuisine: "Chicken,Fast Food",
        rating: 4.3,
        price: "$5 - $20",
        deliveryTime: "15-25 mins",
    },
    {
        id: 5,
        image: "https://kirbiecravings.com/wp-content/uploads/2017/05/avocado-bun-burgers-11a-700x567.jpg",
        restaurantName: "McDonalds",
        cuisine: "Avocado Burger,Fast Food",
        rating: 4.4,
        price: "$5 - $15",
        deliveryTime: "15-25 mins",
    },
    {
        id: 6,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCAM5ef86e2T0d6jyxk2bucf7GwBxhN8JqmQ&s",
        restaurantName: "Subway",
        cuisine: "Sandwich,Fast Food",
        rating: 4.3,
        price: "$5 - $15",
        deliveryTime: "15-25 mins",
    },
    {
        id: 7,
        image: "https://media.istockphoto.com/id/1442417585/photo/person-getting-a-piece-of-cheesy-pepperoni-pizza.jpg?s=612x612&w=0&k=20&c=k60TjxKIOIxJpd4F4yLMVjsniB4W1BpEV4Mi_nb4uJU=",
        restaurantName: "Dominos",
        cuisine: "Pizza,Italian",
        rating: 4.6,
        price: "$5 - $20",
        deliveryTime: "15-25 mins",
    },
    {
        id: 8,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSf1WUoAZgVgyK-R3b6727x0eYKDwhuq-Ro_Q&s",
        restaurantName: "Chick-fil-A",
        cuisine: "Chicken lollipop,Fast Food",
        rating: 4.7,
        price: "$5 - $20",
        deliveryTime: "15-25 mins",
    },
    {
        id: 9,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3qVn_Z__YXx_Uxi5z3z028R3blJIZ8yS8OA&s",
        restaurantName: "Taco Bell",
        cuisine: "Mexican Noodles,Fast Food",
        rating: 4.3,
        price: "$5 - $15",
        deliveryTime: "15-25 mins",
    },
    {
        id: 10,
        image: "https://d2jx2rerrg6sh3.cloudfront.net/images/news/ImageForNews_762330_16980112341128550.jpg",
        restaurantName: "Starbucks",
        cuisine: "Coffee,Tea",
        rating: 4.5,
        price: "$5 - $10",
        deliveryTime: "10-20 mins",
    },
    {
        id: 11,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuSpH1AHiP3ViBOt4ng7z9kHDv2lFdTf1M0Q&s",
        restaurantName: "Spicy Delights",
        cuisine: "Grill Chicken,Indian",
        rating: 4.5,
        price: "$10 - $25",
        deliveryTime: "30-40 mins",
      },
      {
        id: 12,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmgbMNTApICag3wBeDZsA7331wLnEMi9pPBw&s",
        restaurantName: "Soup Haven",
        cuisine: "Veg Soup,Indian",
        rating: 4.7,
        price: "$8 - $20",
        deliveryTime: "20-30 mins"  
      } 
  ];

  export default resObj;